# Generated by Django 3.2 on 2021-05-02 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Author', models.CharField(max_length=100)),
                ('Genre', models.CharField(choices=[('F', 'Fantasy'), ('D', 'Dystopian'), ('S', 'Science fiction'), ('M', 'Mystery'), ('H', 'Horror'), ('R', 'Romance')], max_length=40)),
                ('Type', models.CharField(choices=[('P', 'Physical'), ('E', 'Ebook')], max_length=40)),
                ('Rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Review', models.CharField(max_length=100)),
                ('Favorite', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_books.userprofile')),
            ],
        ),
    ]
